#BEGIN_LEGAL
#
#Copyright (c) 2023 Intel Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  
#END_LEGAL
name: Load Matrix of strategy
description: Load Matrix of strategy
inputs:
  matrix_kind:
    description: 'set test matrix kind (sanity, nightly or Coverity)'
    required: true
    type: string
outputs:
  matrix:
    description: "strategy matrix in Json format"
    value: ${{ steps.matrix_json.outputs.json }}
  matrix_table:
    description: "strategy matrix in html table format"
    value: ${{ steps.matrix_table.outputs.table }}
runs:
  using: composite
  steps:
    - name: Generate test Json matrix 
      shell: bash
      id: matrix_json
      run: |
        JSON=$(python3 .github/scripts/gen_matrix.py --${{inputs.matrix_kind}})
        echo $JSON
        echo "json=${JSON//%/%25}" >> $GITHUB_OUTPUT
    - name: Generate test html table matrix
      shell: bash
      id: matrix_table
      run: |
        TABLE=$(python3 .github/scripts/gen_matrix.py --${{inputs.matrix_kind}} --html)
        echo $TABLE
        echo "table=${TABLE//%/%25}" >> $GITHUB_OUTPUT    
